version: "3.0"

services:
  
  app:
    container_name: app
    build: .
    command: bash -c "cd app && uvicorn main:app --reload --port 8007"
    volumes:
      - .:/app
    ports:
      - 8007:8007
    network_mode: host
    restart: always